/* tslint:disable */
/* eslint-disable */
/**
 * SpeedhivePracticeApi v1.8.58.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface ActivityExclLocationDto
 */
export interface ActivityExclLocationDto {
  /**
   * @type {number}
   * @memberof ActivityExclLocationDto
   */
  id?: number

  /**
   * @type {string}
   * @memberof ActivityExclLocationDto
   */
  name?: string

  /**
   * @type {Date}
   * @memberof ActivityExclLocationDto
   */
  startTime?: Date

  /**
   * @type {Date}
   * @memberof ActivityExclLocationDto
   */
  endTime?: Date

  /**
   * @type {number}
   * @memberof ActivityExclLocationDto
   */
  frameType?: number

  /**
   * @type {number}
   * @memberof ActivityExclLocationDto
   */
  accountId?: number

  /**
   * @type {string}
   * @memberof ActivityExclLocationDto
   */
  gaUId?: string

  /**
   * @type {string}
   * @memberof ActivityExclLocationDto
   */
  chipLabel?: string

  /**
   * @type {string}
   * @memberof ActivityExclLocationDto
   */
  chipCode?: string
}
