/* tslint:disable */
/* eslint-disable */
/**
 * SpeedhivePracticeApi v1.8.58.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ActivityExclLocationDto } from './activity-excl-location-dto'
import { LocationDto } from './location-dto'
/**
 *
 *
 * @export
 * @interface ActivitiesInfoDto
 */
export interface ActivitiesInfoDto {
  /**
   * @type {LocationDto}
   * @memberof ActivitiesInfoDto
   */
  location?: LocationDto

  /**
   * @type {Array<ActivityExclLocationDto>}
   * @memberof ActivitiesInfoDto
   */
  activities?: Array<ActivityExclLocationDto>

  /**
   * @type {number}
   * @memberof ActivitiesInfoDto
   */
  activityCount?: number
}
