/* tslint:disable */
/* eslint-disable */
/**
 * SpeedhivePracticeApi v1.8.58.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ChipDto } from './chip-dto'
import { SpeedDto } from './speed-dto'
/**
 *
 *
 * @export
 * @interface ActivityStatsDto
 */
export interface ActivityStatsDto {
  /**
   * @type {number}
   * @memberof ActivityStatsDto
   */
  lapCount?: number

  /**
   * @type {string}
   * @memberof ActivityStatsDto
   */
  fastestTime?: string

  /**
   * @type {string}
   * @memberof ActivityStatsDto
   */
  averageTime?: string

  /**
   * @type {string}
   * @memberof ActivityStatsDto
   */
  medianTime?: string

  /**
   * @type {string}
   * @memberof ActivityStatsDto
   */
  totalTrainingTime?: string

  /**
   * @type {string}
   * @memberof ActivityStatsDto
   */
  activeTrainingTime?: string

  /**
   * @type {SpeedDto}
   * @memberof ActivityStatsDto
   */
  averageSpeed?: SpeedDto

  /**
   * @type {SpeedDto}
   * @memberof ActivityStatsDto
   */
  fastestSpeed?: SpeedDto

  /**
   * @type {ChipDto}
   * @memberof ActivityStatsDto
   */
  chip?: ChipDto
}
