/* tslint:disable */
/* eslint-disable */
/**
 * SpeedhivePracticeApi v1.8.58.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface ChipDto
 */
export interface ChipDto {
  /**
   * @type {string}
   * @memberof ChipDto
   */
  code?: string

  /**
   * @type {number}
   * @memberof ChipDto
   */
  codeNr?: number

  /**
   * @type {number}
   * @memberof ChipDto
   */
  carId?: number

  /**
   * @type {number}
   * @memberof ChipDto
   */
  id?: number
}
