/* tslint:disable */
/* eslint-disable */
/**
 * SpeedhivePracticeApi v1.8.58.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SectionDto } from './section-dto'
/**
 *
 *
 * @export
 * @interface LocationDto
 */
export interface LocationDto {
  /**
   * @type {string}
   * @memberof LocationDto
   */
  name?: string

  /**
   * @type {number}
   * @memberof LocationDto
   */
  id?: number

  /**
   * @type {string}
   * @memberof LocationDto
   */
  description?: string

  /**
   * @type {string}
   * @memberof LocationDto
   */
  url?: string

  /**
   * @type {number}
   * @memberof LocationDto
   */
  trackLength?: number

  /**
   * @type {string}
   * @memberof LocationDto
   */
  status?: LocationDtoStatusEnum

  /**
   * @type {string}
   * @memberof LocationDto
   */
  sport?: LocationDtoSportEnum

  /**
   * @type {string}
   * @memberof LocationDto
   */
  country?: string

  /**
   * @type {number}
   * @memberof LocationDto
   */
  x2ServiceId?: number

  /**
   * @type {string}
   * @memberof LocationDto
   */
  ipAddress?: string

  /**
   * @type {Array<SectionDto>}
   * @memberof LocationDto
   */
  sections?: Array<SectionDto>
}

/**
 * @export
 * @enum {string}
 */
export enum LocationDtoStatusEnum {
  UNKNOWN = 'UNKNOWN',
  OFFLINE = 'OFFLINE',
  ONLINE = 'ONLINE',
  ACTIVE = 'ACTIVE',
}
/**
 * @export
 * @enum {string}
 */
export enum LocationDtoSportEnum {
  Unknown = 'Unknown',
  Karting = 'Karting',
  MX = 'MX',
  Car = 'Car',
  Bike = 'Bike',
  RC = 'RC',
  Cycling = 'Cycling',
  IceSkating = 'IceSkating',
  Running = 'Running',
  ModelBoatRacing = 'ModelBoatRacing',
  InlineSkating = 'InlineSkating',
  StockCar = 'StockCar',
  Swimming = 'Swimming',
  Other = 'Other',
}
