/* tslint:disable */
/* eslint-disable */
/**
 * SpeedhivePracticeApi v1.8.58.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface PracticeSessionDto
 */
export interface PracticeSessionDto {
  /**
   * @type {number}
   * @memberof PracticeSessionDto
   */
  id?: number

  /**
   * @type {number}
   * @memberof PracticeSessionDto
   */
  locationId?: number

  /**
   * @type {number}
   * @memberof PracticeSessionDto
   */
  starttimeutc?: number

  /**
   * @type {number}
   * @memberof PracticeSessionDto
   */
  endtimeutc?: number

  /**
   * @type {number}
   * @memberof PracticeSessionDto
   */
  starttimelocal?: number

  /**
   * @type {number}
   * @memberof PracticeSessionDto
   */
  endtimelocal?: number
}
