/* tslint:disable */
/* eslint-disable */
/**
 * SpeedhivePracticeApi v1.8.58.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BestLapDto } from './best-lap-dto'
import { LapDto } from './lap-dto'
/**
 *
 *
 * @export
 * @interface SessionDto
 */
export interface SessionDto {
  /**
   * @type {number}
   * @memberof SessionDto
   */
  id?: number

  /**
   * @type {number}
   * @memberof SessionDto
   */
  chipId?: number

  /**
   * @type {Date}
   * @memberof SessionDto
   */
  dateTimeStart?: Date

  /**
   * @type {BestLapDto}
   * @memberof SessionDto
   */
  bestLap?: BestLapDto

  /**
   * @type {string}
   * @memberof SessionDto
   */
  aveLapDuration?: string

  /**
   * @type {string}
   * @memberof SessionDto
   */
  medianLapDuration?: string

  /**
   * @type {string}
   * @memberof SessionDto
   */
  duration?: string

  /**
   * @type {Array<LapDto>}
   * @memberof SessionDto
   */
  laps?: Array<LapDto>
}
