/* tslint:disable */
/* eslint-disable */
/**
 * SpeedhivePracticeApi v1.8.58.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface SportListDto
 */
export interface SportListDto {
  /**
   * @type {Array<string>}
   * @memberof SportListDto
   */
  sports?: Array<SportListDtoSportsEnum>
}

/**
 * @export
 * @enum {string}
 */
export enum SportListDtoSportsEnum {
  Unknown = 'Unknown',
  Karting = 'Karting',
  MX = 'MX',
  Car = 'Car',
  Bike = 'Bike',
  RC = 'RC',
  Cycling = 'Cycling',
  IceSkating = 'IceSkating',
  Running = 'Running',
  ModelBoatRacing = 'ModelBoatRacing',
  InlineSkating = 'InlineSkating',
  StockCar = 'StockCar',
  Swimming = 'Swimming',
  Other = 'Other',
}
